sonar.projectKey=Luan-zanardo_integration-tests-jest-api
sonar.organization=luan-zanardo
sonar.projectName=integration-tests-jest-api
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8